package com.example.urlShortner.Controller;

import com.example.urlShortner.Common.UrlUtil;
import com.example.urlShortner.DTO.FullUrl;
import com.example.urlShortner.DTO.ShortUrl;
import com.example.urlShortner.Error.InvalidUrlError;
import com.example.urlShortner.Service.UrlService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.apache.commons.validator.routines.UrlValidator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.NoSuchElementException;


@RestController
public class UrlController {

    Logger logger= LoggerFactory.getLogger(UrlController.class);
    protected final UrlService urlService;

    @Autowired
    public UrlController(UrlService urlService) {
        this.urlService = urlService;
    }

    /*
        @param fullUrl Takes an Object of FullUrl Supplied in the RequestBody
        @param request To determine the protocol://domain:port part to form shortened url
        @return An object of ShortUrl serialized as JSON in the response
     */
    @PostMapping("/shorten")
    public ResponseEntity<Object>saveURL(@RequestBody FullUrl fullUrl, HttpServletRequest request) {
        //This class is from Commons Validator dependency
        //Validation checks to determine if the Supplied URL is valid

        UrlValidator validator = new UrlValidator(
                new String[]{"http","https"}
        );

        String url = fullUrl.getFullUrl();

        if(!validator.isValid(url)){ //If not a Valid URL
            logger.error("Malformed URL Provided");
            InvalidUrlError error = new InvalidUrlError("url",fullUrl.getFullUrl(),"Invalid URL");
            return ResponseEntity.badRequest().body(error);
        }

        //If a Valid URL
        String baseURL= null;
        try {
            baseURL = UrlUtil.getBaseURL(request.getRequestURL().toString());
        } catch (MalformedURLException e) {
            logger.error("Malformed Request URL");
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Request URL is Not Valid",e);
        }

        ShortUrl shortUrl = urlService.getShortURL(fullUrl);
        shortUrl.setShortUrl(baseURL+ shortUrl.getShortUrl());
        logger.info("ShortURL for FullURL {} is {}.",fullUrl.getFullUrl(),shortUrl.getShortUrl());

        return new ResponseEntity<>(shortUrl,HttpStatus.OK);
    }

    /*
        @param response HttpServletResponse - Used to Redirect to Full URL
        @shortenString - Base62 encoded String Generated by '/shorten' endpoint
     */
    @GetMapping("/{shortenString}")
    public void redirectToFullUrl(HttpServletResponse response, @PathVariable String shortenString){
        try{
            FullUrl fullUrl = urlService.getFullURL(shortenString);
            logger.info("redirecting to full URL: {}",fullUrl.getFullUrl());
            response.sendRedirect(fullUrl.getFullUrl());
        } catch (NoSuchElementException e) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Url Not Found",e);
        } catch (IOException e){
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"Could Not redirect to full url",e);
        }
    }
}



